fix: updated workflow file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,18 +38,18 @@ jobs:
           fi
 
           # Test case 3:
-          # echo "Running Test-3: out-of-range (-1)"
-          # echo -1 | ./fibo.sh > file.txt 
-          # if grep -q "Invalid" file.txt; then
-          #  echo "Test-3 passed"
-          # else
-          #  echo "Test-3 failed" && exit 3
-          # fi
+          echo "Running Test-3: out-of-range (-1)"
+          echo -1 | ./fibo.sh | head -n 1 > file.txt 
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
+           echo "Test-3 passed"
+          else
+           echo "Test-3 failed" && exit 3
+          fi
 
           # Test case 4:
           echo "Running Test-4: out-of-range (501)"
-          echo 501 | ./fibo.sh > file.txt
-          if grep -q "Invalid" file.txt; then
+          echo 501 | ./fibo.sh | head -n 1  > file.txt
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
             echo "Test-4 passed"
           else 
             echo "Test-4 failed" && exit 4
@@ -57,8 +57,8 @@ jobs:
 
           # Test case 5: 
           echo "Running Test-5: Invalid Input (a)"
-          echo a | ./fibo.sh > file.txt
-          if grep -q "Invalid" file.txt; then
+          echo a | ./fibo.sh | head -n 1 > file.txt
+          if grep -q "Invalid input. Please enter a number between 0 and 500." file.txt; then
             echo "Test-5 passed"
           else
             echo "Test-5 failed" && exit 5
